version: '3.8'

x-common-variables: &common-variables
  COMPOSE_CONVERT_WINDOWS_PATHS: 1

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cartorio-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3000
      - VITE_AUTH_SERVICE_URL=http://localhost:3001
      - VITE_USER_SERVICE_URL=http://localhost:3002
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - cartorio-network

networks:
  cartorio-network:
    driver: bridge
