version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: cartorio-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-cartorio}
      MYSQL_USER: ${MYSQL_USER:-cartorio}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-cartorio123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis para cache e sessões
  redis:
    image: redis:7-alpine
    container_name: cartorio-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  # Serviço de Autenticação
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: cartorio-auth-service
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER:-cartorio}:${MYSQL_PASSWORD:-cartorio123}@mysql:3306/${MYSQL_DATABASE:-cartorio}
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      timeout: 5s
      retries: 3

  # Serviço de Usuários
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: cartorio-user-service
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER:-cartorio}:${MYSQL_PASSWORD:-cartorio123}@mysql:3306/${MYSQL_DATABASE:-cartorio}
      - PORT=3002
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      timeout: 5s
      retries: 3

  # Serviço de Protocolos
  protocolo-service:
    build:
      context: ./services/protocolo-service
      dockerfile: Dockerfile
    container_name: cartorio-protocolo-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER:-cartorio}:${MYSQL_PASSWORD:-cartorio123}@mysql:3306/${MYSQL_DATABASE:-cartorio}
      - PORT=3003
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/health"]
      timeout: 5s
      retries: 3

  # Serviço de Clientes
  cliente-service:
    build:
      context: ./services/cliente-service
      dockerfile: Dockerfile
    container_name: cartorio-cliente-service
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://${MYSQL_USER:-cartorio}:${MYSQL_PASSWORD:-cartorio123}@mysql:3306/${MYSQL_DATABASE:-cartorio}
      - PORT=3004
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      timeout: 5s
      retries: 3

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: cartorio-api-gateway
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - PROTOCOLO_SERVICE_URL=http://protocolo-service:3003
      - CLIENTE_SERVICE_URL=http://cliente-service:3004
      - REDIS_URL=redis://redis:6379
    depends_on:
      - auth-service
      - user-service
      - protocolo-service
      - cliente-service
      - redis
    networks:
      - cartorio-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      timeout: 5s
      retries: 3

  # Frontend (Nginx)
  nginx:
    image: nginx:alpine
    container_name: cartorio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-gateway
    networks:
      - cartorio-network

  # Prometheus para monitoramento
  prometheus:
    image: prom/prometheus:latest
    container_name: cartorio-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - cartorio-network

  # Grafana para dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: cartorio-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - cartorio-network

volumes:
  mysql_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  cartorio-network:
    driver: bridge
