version: '3.8'

# Configurações específicas para Windows
x-common-variables: &common-variables
  COMPOSE_CONVERT_WINDOWS_PATHS: 1

services:
  # Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: cartorio-postgres
    environment:
      POSTGRES_DB: cartorio_db
      POSTGRES_USER: cartorio_user
      POSTGRES_PASSWORD: cartorio_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - cartorio-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: cartorio-auth-service
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://cartorio_user:cartorio_password@postgres:5432/cartorio_db
      JWT_SECRET: your-super-secret-jwt-key
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - cartorio-network

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: cartorio-user-service
    environment:
      NODE_ENV: development
      PORT: 3002
      DATABASE_URL: postgresql://cartorio_user:cartorio_password@postgres:5432/cartorio_db
    ports:
      - "3002:3002"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - cartorio-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: cartorio-api-gateway
    environment:
      NODE_ENV: development
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      USER_SERVICE_URL: http://user-service:3002
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - auth-service
      - user-service
    networks:
      - cartorio-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cartorio-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
    ports:
      - "3007:3000"
    restart: unless-stopped
    depends_on:
      - api-gateway
    networks:
      - cartorio-network

volumes:
  postgres_data:

networks:
  cartorio-network:
    driver: bridge
