// Exportar todos os ícones personalizados
export { default as Icon } from './Icon';

// Exportar ícones específicos do sistema de cartório
export {
  DocumentIcon,
  RegistryIcon,
  CertificateIcon,
  PaymentIcon,
  BuildingIcon,
  UserIcon,
  SearchIcon,
  SettingsIcon,
  NotificationsIcon,
  DashboardIcon,
  CloseIcon,
  EditIcon,
  DeleteIcon,
  SaveIcon,
  PrintIcon,
  DownloadIcon,
  UploadIcon,
  CalendarIcon,
  ClockIcon,
  CheckIcon,
  PlusIcon,
  MinusIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  HomeIcon,
  LogoutIcon,
  LoginIcon,
  LockIcon,
  UnlockIcon,
  EyeIcon,
  EyeOffIcon,
  FilterIcon,
  SortIcon,
  RefreshIcon,
  StarIcon,
  HeartIcon,
  BookmarkIcon,
  ShareIcon,
  CopyIcon,
  LinkIcon,
  ExternalLinkIcon,
  InfoIcon,
  WarningIcon,
  ErrorIcon,
  SuccessIcon,
  FirmasIcon,
  MarriageIcon,
  BabyIcon,
  XIcon,
  CalculatorIcon,
  TrashIcon,
  MenuIcon
} from './CartorioIcons';
