/**
 * Opções compartilhadas para dropdowns de UF e País
 * Usado em todas as páginas do sistema
 */

// Opções para UF (Estados Brasileiros)
export const UF_OPTIONS = [
  { value: '', label: 'Selecione' },
  { value: 'AC', label: 'AC - Acre' },
  { value: 'AL', label: 'AL - Alagoas' },
  { value: 'AP', label: 'AP - Amapá' },
  { value: 'AM', label: 'AM - Amazonas' },
  { value: 'BA', label: 'BA - Bahia' },
  { value: 'CE', label: 'CE - Ceará' },
  { value: 'DF', label: 'DF - Distrito Federal' },
  { value: 'ES', label: 'ES - Espírito Santo' },
  { value: 'GO', label: 'GO - Goiás' },
  { value: 'MA', label: 'MA - Maranhão' },
  { value: 'MT', label: 'MT - Mato Grosso' },
  { value: 'MS', label: 'MS - Mato Grosso do Sul' },
  { value: 'MG', label: 'MG - Minas Gerais' },
  { value: 'PA', label: 'PA - Pará' },
  { value: 'PB', label: 'PB - Paraíba' },
  { value: 'PR', label: 'PR - Paraná' },
  { value: 'PE', label: 'PE - Pernambuco' },
  { value: 'PI', label: 'PI - Piauí' },
  { value: 'RJ', label: 'RJ - Rio de Janeiro' },
  { value: 'RN', label: 'RN - Rio Grande do Norte' },
  { value: 'RS', label: 'RS - Rio Grande do Sul' },
  { value: 'RO', label: 'RO - Rondônia' },
  { value: 'RR', label: 'RR - Roraima' },
  { value: 'SC', label: 'SC - Santa Catarina' },
  { value: 'SP', label: 'SP - São Paulo' },
  { value: 'SE', label: 'SE - Sergipe' },
  { value: 'TO', label: 'TO - Tocantins' }
]

// Opções para País - Lista completa de países
export const PAIS_OPTIONS = [
  { value: '', label: 'Selecione' },
  { value: 'AF', label: 'AF - Afeganistão' },
  { value: 'ZA', label: 'ZA - África do Sul' },
  { value: 'AL', label: 'AL - Albânia' },
  { value: 'DE', label: 'DE - Alemanha' },
  { value: 'AD', label: 'AD - Andorra' },
  { value: 'AO', label: 'AO - Angola' },
  { value: 'AI', label: 'AI - Anguilla' },
  { value: 'AQ', label: 'AQ - Antártida' },
  { value: 'AG', label: 'AG - Antígua e Barbuda' },
  { value: 'SA', label: 'SA - Arábia Saudita' },
  { value: 'DZ', label: 'DZ - Argélia' },
  { value: 'AR', label: 'AR - Argentina' },
  { value: 'AM', label: 'AM - Armênia' },
  { value: 'AW', label: 'AW - Aruba' },
  { value: 'AU', label: 'AU - Austrália' },
  { value: 'AT', label: 'AT - Áustria' },
  { value: 'AZ', label: 'AZ - Azerbaijão' },
  { value: 'BS', label: 'BS - Bahamas' },
  { value: 'BH', label: 'BH - Bahrein' },
  { value: 'BD', label: 'BD - Bangladesh' },
  { value: 'BB', label: 'BB - Barbados' },
  { value: 'BY', label: 'BY - Belarus' },
  { value: 'BE', label: 'BE - Bélgica' },
  { value: 'BZ', label: 'BZ - Belize' },
  { value: 'BJ', label: 'BJ - Benin' },
  { value: 'BM', label: 'BM - Bermudas' },
  { value: 'BO', label: 'BO - Bolívia' },
  { value: 'BA', label: 'BA - Bósnia e Herzegovina' },
  { value: 'BW', label: 'BW - Botswana' },
  { value: 'BR', label: 'BR - Brasil' },
  { value: 'BN', label: 'BN - Brunei' },
  { value: 'BG', label: 'BG - Bulgária' },
  { value: 'BF', label: 'BF - Burkina Faso' },
  { value: 'BI', label: 'BI - Burundi' },
  { value: 'BT', label: 'BT - Butão' },
  { value: 'CV', label: 'CV - Cabo Verde' },
  { value: 'KH', label: 'KH - Camboja' },
  { value: 'CM', label: 'CM - Camarões' },
  { value: 'CA', label: 'CA - Canadá' },
  { value: 'KZ', label: 'KZ - Cazaquistão' },
  { value: 'TD', label: 'TD - Chade' },
  { value: 'CL', label: 'CL - Chile' },
  { value: 'CN', label: 'CN - China' },
  { value: 'CY', label: 'CY - Chipre' },
  { value: 'CO', label: 'CO - Colômbia' },
  { value: 'KM', label: 'KM - Comores' },
  { value: 'CG', label: 'CG - Congo' },
  { value: 'CD', label: 'CD - Congo (República Democrática)' },
  { value: 'KP', label: 'KP - Coreia do Norte' },
  { value: 'KR', label: 'KR - Coreia do Sul' },
  { value: 'CI', label: 'CI - Costa do Marfim' },
  { value: 'CR', label: 'CR - Costa Rica' },
  { value: 'HR', label: 'HR - Croácia' },
  { value: 'CU', label: 'CU - Cuba' },
  { value: 'CW', label: 'CW - Curaçao' },
  { value: 'DK', label: 'DK - Dinamarca' },
  { value: 'DJ', label: 'DJ - Djibuti' },
  { value: 'DM', label: 'DM - Dominica' },
  { value: 'EG', label: 'EG - Egito' },
  { value: 'SV', label: 'SV - El Salvador' },
  { value: 'AE', label: 'AE - Emirados Árabes Unidos' },
  { value: 'EC', label: 'EC - Equador' },
  { value: 'ER', label: 'ER - Eritreia' },
  { value: 'SK', label: 'SK - Eslováquia' },
  { value: 'SI', label: 'SI - Eslovênia' },
  { value: 'ES', label: 'ES - Espanha' },
  { value: 'US', label: 'US - Estados Unidos' },
  { value: 'EE', label: 'EE - Estônia' },
  { value: 'ET', label: 'ET - Etiópia' },
  { value: 'FJ', label: 'FJ - Fiji' },
  { value: 'PH', label: 'PH - Filipinas' },
  { value: 'FI', label: 'FI - Finlândia' },
  { value: 'FR', label: 'FR - França' },
  { value: 'GA', label: 'GA - Gabão' },
  { value: 'GM', label: 'GM - Gâmbia' },
  { value: 'GH', label: 'GH - Gana' },
  { value: 'GE', label: 'GE - Geórgia' },
  { value: 'GI', label: 'GI - Gibraltar' },
  { value: 'GD', label: 'GD - Granada' },
  { value: 'GR', label: 'GR - Grécia' },
  { value: 'GL', label: 'GL - Groenlândia' },
  { value: 'GP', label: 'GP - Guadalupe' },
  { value: 'GU', label: 'GU - Guam' },
  { value: 'GT', label: 'GT - Guatemala' },
  { value: 'GG', label: 'GG - Guernsey' },
  { value: 'GY', label: 'GY - Guiana' },
  { value: 'GF', label: 'GF - Guiana Francesa' },
  { value: 'GN', label: 'GN - Guiné' },
  { value: 'GW', label: 'GW - Guiné-Bissau' },
  { value: 'GQ', label: 'GQ - Guiné Equatorial' },
  { value: 'HT', label: 'HT - Haiti' },
  { value: 'NL', label: 'NL - Holanda' },
  { value: 'HN', label: 'HN - Honduras' },
  { value: 'HK', label: 'HK - Hong Kong' },
  { value: 'HU', label: 'HU - Hungria' },
  { value: 'YE', label: 'YE - Iêmen' },
  { value: 'BV', label: 'BV - Ilha Bouvet' },
  { value: 'CX', label: 'CX - Ilha Christmas' },
  { value: 'IM', label: 'IM - Ilha de Man' },
  { value: 'NF', label: 'NF - Ilha Norfolk' },
  { value: 'AX', label: 'AX - Ilhas Åland' },
  { value: 'KY', label: 'KY - Ilhas Cayman' },
  { value: 'CC', label: 'CC - Ilhas Cocos' },
  { value: 'CK', label: 'CK - Ilhas Cook' },
  { value: 'FO', label: 'FO - Ilhas Faroe' },
  { value: 'GS', label: 'GS - Ilhas Geórgia do Sul e Sandwich do Sul' },
  { value: 'HM', label: 'HM - Ilhas Heard e McDonald' },
  { value: 'FK', label: 'FK - Ilhas Malvinas' },
  { value: 'MP', label: 'MP - Ilhas Marianas do Norte' },
  { value: 'MH', label: 'MH - Ilhas Marshall' },
  { value: 'UM', label: 'UM - Ilhas Menores Distantes dos Estados Unidos' },
  { value: 'PN', label: 'PN - Ilhas Pitcairn' },
  { value: 'SB', label: 'SB - Ilhas Salomão' },
  { value: 'TC', label: 'TC - Ilhas Turcas e Caicos' },
  { value: 'VG', label: 'VG - Ilhas Virgens Britânicas' },
  { value: 'VI', label: 'VI - Ilhas Virgens dos Estados Unidos' },
  { value: 'IN', label: 'IN - Índia' },
  { value: 'ID', label: 'ID - Indonésia' },
  { value: 'IR', label: 'IR - Irã' },
  { value: 'IQ', label: 'IQ - Iraque' },
  { value: 'IE', label: 'IE - Irlanda' },
  { value: 'IS', label: 'IS - Islândia' },
  { value: 'IL', label: 'IL - Israel' },
  { value: 'IT', label: 'IT - Itália' },
  { value: 'JM', label: 'JM - Jamaica' },
  { value: 'JP', label: 'JP - Japão' },
  { value: 'JE', label: 'JE - Jersey' },
  { value: 'JO', label: 'JO - Jordânia' },
  { value: 'KI', label: 'KI - Kiribati' },
  { value: 'KW', label: 'KW - Kuwait' },
  { value: 'LA', label: 'LA - Laos' },
  { value: 'LS', label: 'LS - Lesoto' },
  { value: 'LV', label: 'LV - Letônia' },
  { value: 'LB', label: 'LB - Líbano' },
  { value: 'LR', label: 'LR - Libéria' },
  { value: 'LY', label: 'LY - Líbia' },
  { value: 'LI', label: 'LI - Liechtenstein' },
  { value: 'LT', label: 'LT - Lituânia' },
  { value: 'LU', label: 'LU - Luxemburgo' },
  { value: 'MO', label: 'MO - Macau' },
  { value: 'MK', label: 'MK - Macedônia do Norte' },
  { value: 'MG', label: 'MG - Madagascar' },
  { value: 'MY', label: 'MY - Malásia' },
  { value: 'MW', label: 'MW - Malawi' },
  { value: 'MV', label: 'MV - Maldivas' },
  { value: 'ML', label: 'ML - Mali' },
  { value: 'MT', label: 'MT - Malta' },
  { value: 'MA', label: 'MA - Marrocos' },
  { value: 'MQ', label: 'MQ - Martinica' },
  { value: 'MU', label: 'MU - Maurício' },
  { value: 'MR', label: 'MR - Mauritânia' },
  { value: 'YT', label: 'YT - Mayotte' },
  { value: 'MX', label: 'MX - México' },
  { value: 'FM', label: 'FM - Micronésia' },
  { value: 'MZ', label: 'MZ - Moçambique' },
  { value: 'MD', label: 'MD - Moldávia' },
  { value: 'MC', label: 'MC - Mônaco' },
  { value: 'MN', label: 'MN - Mongólia' },
  { value: 'ME', label: 'ME - Montenegro' },
  { value: 'MS', label: 'MS - Montserrat' },
  { value: 'MM', label: 'MM - Myanmar' },
  { value: 'NA', label: 'NA - Namíbia' },
  { value: 'NR', label: 'NR - Nauru' },
  { value: 'NP', label: 'NP - Nepal' },
  { value: 'NI', label: 'NI - Nicarágua' },
  { value: 'NE', label: 'NE - Níger' },
  { value: 'NG', label: 'NG - Nigéria' },
  { value: 'NU', label: 'NU - Niue' },
  { value: 'NO', label: 'NO - Noruega' },
  { value: 'NC', label: 'NC - Nova Caledônia' },
  { value: 'NZ', label: 'NZ - Nova Zelândia' },
  { value: 'OM', label: 'OM - Omã' },
  { value: 'PW', label: 'PW - Palau' },
  { value: 'PS', label: 'PS - Palestina' },
  { value: 'PA', label: 'PA - Panamá' },
  { value: 'PG', label: 'PG - Papua Nova Guiné' },
  { value: 'PK', label: 'PK - Paquistão' },
  { value: 'PY', label: 'PY - Paraguai' },
  { value: 'PE', label: 'PE - Peru' },
  { value: 'PF', label: 'PF - Polinésia Francesa' },
  { value: 'PL', label: 'PL - Polônia' },
  { value: 'PR', label: 'PR - Porto Rico' },
  { value: 'PT', label: 'PT - Portugal' },
  { value: 'KE', label: 'KE - Quênia' },
  { value: 'KG', label: 'KG - Quirguistão' },
  { value: 'GB', label: 'GB - Reino Unido' },
  { value: 'CF', label: 'CF - República Centro-Africana' },
  { value: 'CZ', label: 'CZ - República Tcheca' },
  { value: 'DO', label: 'DO - República Dominicana' },
  { value: 'RE', label: 'RE - Reunião' },
  { value: 'RO', label: 'RO - Romênia' },
  { value: 'RW', label: 'RW - Ruanda' },
  { value: 'RU', label: 'RU - Rússia' },
  { value: 'EH', label: 'EH - Saara Ocidental' },
  { value: 'WS', label: 'WS - Samoa' },
  { value: 'AS', label: 'AS - Samoa Americana' },
  { value: 'SM', label: 'SM - San Marino' },
  { value: 'SH', label: 'SH - Santa Helena' },
  { value: 'LC', label: 'LC - Santa Lúcia' },
  { value: 'BL', label: 'BL - São Bartolomeu' },
  { value: 'KN', label: 'KN - São Cristóvão e Nevis' },
  { value: 'MF', label: 'MF - São Martinho' },
  { value: 'ST', label: 'ST - São Tomé e Príncipe' },
  { value: 'VC', label: 'VC - São Vicente e Granadinas' },
  { value: 'SN', label: 'SN - Senegal' },
  { value: 'SL', label: 'SL - Serra Leoa' },
  { value: 'RS', label: 'RS - Sérvia' },
  { value: 'SC', label: 'SC - Seychelles' },
  { value: 'SG', label: 'SG - Singapura' },
  { value: 'SY', label: 'SY - Síria' },
  { value: 'SO', label: 'SO - Somália' },
  { value: 'LK', label: 'LK - Sri Lanka' },
  { value: 'SZ', label: 'SZ - Suazilândia' },
  { value: 'SD', label: 'SD - Sudão' },
  { value: 'SS', label: 'SS - Sudão do Sul' },
  { value: 'SE', label: 'SE - Suécia' },
  { value: 'CH', label: 'CH - Suíça' },
  { value: 'SR', label: 'SR - Suriname' },
  { value: 'SJ', label: 'SJ - Svalbard e Jan Mayen' },
  { value: 'TH', label: 'TH - Tailândia' },
  { value: 'TW', label: 'TW - Taiwan' },
  { value: 'TJ', label: 'TJ - Tajiquistão' },
  { value: 'TZ', label: 'TZ - Tanzânia' },
  { value: 'IO', label: 'IO - Território Britânico do Oceano Índico' },
  { value: 'TF', label: 'TF - Territórios Franceses do Sul' },
  { value: 'TL', label: 'TL - Timor-Leste' },
  { value: 'TG', label: 'TG - Togo' },
  { value: 'TK', label: 'TK - Tokelau' },
  { value: 'TO', label: 'TO - Tonga' },
  { value: 'TT', label: 'TT - Trinidad e Tobago' },
  { value: 'TN', label: 'TN - Tunísia' },
  { value: 'TM', label: 'TM - Turcomenistão' },
  { value: 'TR', label: 'TR - Turquia' },
  { value: 'TV', label: 'TV - Tuvalu' },
  { value: 'UA', label: 'UA - Ucrânia' },
  { value: 'UG', label: 'UG - Uganda' },
  { value: 'UY', label: 'UY - Uruguai' },
  { value: 'UZ', label: 'UZ - Uzbequistão' },
  { value: 'VU', label: 'VU - Vanuatu' },
  { value: 'VA', label: 'VA - Vaticano' },
  { value: 'VE', label: 'VE - Venezuela' },
  { value: 'VN', label: 'VN - Vietnã' },
  { value: 'WF', label: 'WF - Wallis e Futuna' },
  { value: 'ZM', label: 'ZM - Zâmbia' },
  { value: 'ZW', label: 'ZW - Zimbábue' }
]

